### PR TITLE
Information about DNS

### PR DESCRIPTION
**Pull request by Farhadzahin123**

### CODE REVIEW

**Comment by Farhadzahin123** [comment]
Create pull request

**Comment by Abdulmateenmaher** [comment]
i change some information please pull request

**Comment by Farhadzahin123** [comment]
Seconde full request

**Comment by Farhadzahin123** [comment]
Seconds full request

**Comment by Farhadzahin123** [comment]
DNS
DNS (Domain name system) Is a network protocol used to translate hostname into IP address 
DNS is not required establish a network connection.
DNS has to step 
 Forward lookup zone: uses the domain name to search for IP address 
Server.exmple.com
192.168.23.1
 Revers lookup zone: use IP address to search for the domain name .

**Pull request closed without merging**
